num1 = int(input('Enter first Number: '))
num2 = int(input('Enter second number: '))
num3 = int(input('Enter third Number: '))
num4 = int(input('Enter fourth number: '))
num5 = int(input('Enter fifth Number: '))
print(f'{num1}\t {num2}\t {num3}\t {num4}\t {num5}')